/*
 * apimaticcalculator
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/28/2016
 */

package simplecalculator


import "apimaticcalculator/models"

/*
 * Interface for the SIMPLECALCULATOR_IMPL
 */
type SIMPLECALCULATOR interface {
    GetCalculate (*GetCalculateInput) (float32, error)
}

/*
 * Factory for the SIMPLECALCULATOR interaface returning SIMPLECALCULATOR_IMPL
 */
func NewSIMPLECALCULATOR() SIMPLECALCULATOR {
    return &SIMPLECALCULATOR_IMPL{}
}