/*
 * digitalnewzealand
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/28/2016
 */

package metadata


import "digitalnewzealand/models"

/*
 * Interface for the METADATA_IMPL
 */
type METADATA interface {
    GetMetadata (*GetMetadataInput) (*models.CollectionSearchRecords, error)
}

/*
 * Factory for the METADATA interaface returning METADATA_IMPL
 */
func NewMETADATA() METADATA {
    return &METADATA_IMPL{}
}