/*
 * apimaticcalculator
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 06/28/2016
 */
package models

/**
 * Type definition for OperationTypeEnum enum
 */
type OperationTypeEnum int

/**
 * Value collection for OperationTypeEnum enum
 */
const (
    OperationType_SUM OperationTypeEnum = 1 + iota
    OperationType_SUBTRACT
    OperationType_MULTIPLY
    OperationType_DIVIDE
)

/**
 * Converts OperationTypeEnum to its string representation
 */
func OperationTypeEnumToValue(operationTypeEnum OperationTypeEnum) string {
	switch operationTypeEnum {
		case OperationType_SUM:
			return "SUM"
		case OperationType_SUBTRACT:
			return "SUBTRACT"
		case OperationType_MULTIPLY:
			return "MULTIPLY"
		case OperationType_DIVIDE:
			return "DIVIDE"
        default:
            return "SUM"
	}
}

/**
 * Converts given value to its enum representation
 */
func OperationTypeEnumFromValue(value string) OperationTypeEnum {
	switch value {
		case "SUM":
			return OperationType_SUM
		case "SUBTRACT":
			return OperationType_SUBTRACT
		case "MULTIPLY":
			return OperationType_MULTIPLY
		case "DIVIDE":
			return OperationType_DIVIDE
        default:
            return OperationType_SUM
	}
}
