/**
 *DigitalNewzealandLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 07/04/2016
 */

'use strict';
angular.module('DigitalNewzealandLib',[]).factory('Configuration', function() {
    return {
        //The base Uri for API calls
        BASEURI : "http://api.digitalnz.org",

        //Your API Key
        //TODO: Replace the apiKey with an appropriate value
        apiKey : "TODO: Replace"

    };
});

